// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3v3cPVpibccGzFfD8vBax4wD14NO5J8Y',
    appId: '1:996100752806:web:afbb9171ccc3478efafb67',
    messagingSenderId: '996100752806',
    projectId: 'kolektt',
    authDomain: 'kolektt.firebaseapp.com',
    storageBucket: 'kolektt.firebasestorage.app',
    measurementId: 'G-MZ3P7F7ZRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwsJo2TgYU4NVMN4O-E07UBJe9NiZfcY0',
    appId: '1:996100752806:android:1c3c6e53266b3d56fafb67',
    messagingSenderId: '996100752806',
    projectId: 'kolektt',
    storageBucket: 'kolektt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJHSRQjnmY2KtoTyV1cf7HWL1aPz58vB0',
    appId: '1:996100752806:ios:2e9f4834caae22cffafb67',
    messagingSenderId: '996100752806',
    projectId: 'kolektt',
    storageBucket: 'kolektt.firebasestorage.app',
    androidClientId: '996100752806-88rp4jvf00lqj6a3m0h432mrsctv645p.apps.googleusercontent.com',
    iosClientId: '996100752806-8b8ulnkli19fna1rvd18hktt206h5h7k.apps.googleusercontent.com',
    iosBundleId: 'com.kolektt.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJHSRQjnmY2KtoTyV1cf7HWL1aPz58vB0',
    appId: '1:996100752806:ios:16370484e949e41efafb67',
    messagingSenderId: '996100752806',
    projectId: 'kolektt',
    storageBucket: 'kolektt.firebasestorage.app',
    androidClientId: '996100752806-88rp4jvf00lqj6a3m0h432mrsctv645p.apps.googleusercontent.com',
    iosBundleId: 'com.example.kolektt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3v3cPVpibccGzFfD8vBax4wD14NO5J8Y',
    appId: '1:996100752806:web:3d97758c020002e5fafb67',
    messagingSenderId: '996100752806',
    projectId: 'kolektt',
    authDomain: 'kolektt.firebaseapp.com',
    storageBucket: 'kolektt.firebasestorage.app',
    measurementId: 'G-0NPJE4X7QX',
  );

}